@baseUrl = http://localhost:52774/terminology/fhir/r4
@username = superuser
@password = SYS
@systemUrl = http://loinc.org
@codeSystemId = loinc
@conceptCode = 718-7
@ancestorCode = LP392452-1

### CapabilityStatement
GET {{baseUrl}}/metadata
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### TODO: TerminologyCapabilities
GET {{baseUrl}}/metadata?mode=terminology
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### CodeSystem read by id
GET {{baseUrl}}/CodeSystem/{{codeSystemId}}
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### CodeSystem search
GET {{baseUrl}}/CodeSystem
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### CodeSystem search by url
GET {{baseUrl}}/CodeSystem?url={{systemUrl}}
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### CodeSystem search by name
GET {{baseUrl}}/CodeSystem?name=LOINC
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### CodeSystem $lookup by code
GET {{baseUrl}}/CodeSystem/$lookup?system={{systemUrl}}&code={{conceptCode}}&displayLanguage=es
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### CodeSystem instance $lookup by code
GET {{baseUrl}}/CodeSystem/{{codeSystemId}}/$lookup?code={{conceptCode}}&displayLanguage=es
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### CodeSystem $validate-code by code
GET {{baseUrl}}/CodeSystem/$validate-code?system={{systemUrl}}&code={{conceptCode}}
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### CodeSystem instance $validate-code by code
GET {{baseUrl}}/CodeSystem/{{codeSystemId}}/$validate-code?code={{conceptCode}}
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### CodeSystem $validate-code invalid example
GET {{baseUrl}}/CodeSystem/$validate-code?system={{systemUrl}}&code=9999999999-INVALID
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### CodeSystem $subsumes by code pair
GET {{baseUrl}}/CodeSystem/$subsumes?system={{systemUrl}}&codeA={{ancestorCode}}&codeB={{conceptCode}}
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### CodeSystem instance $subsumes by code pair
GET {{baseUrl}}/CodeSystem/{{codeSystemId}}/$subsumes?codeA={{ancestorCode}}&codeB={{conceptCode}}
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### CodeSystem $subsumes equivalent example
GET {{baseUrl}}/CodeSystem/$subsumes?system={{systemUrl}}&codeA={{conceptCode}}&codeB={{conceptCode}}
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### CodeSystem $subsumes reverse direction
GET {{baseUrl}}/CodeSystem/$subsumes?system={{systemUrl}}&codeA={{conceptCode}}&codeB={{ancestorCode}}
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### ValueSet search by _id
GET {{baseUrl}}/ValueSet?_id=loinc-group-LG51020-2
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### ValueSet search by url
GET {{baseUrl}}/ValueSet?url=http://loinc.org/vs/LG51020-2
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### ValueSet search by name
GET {{baseUrl}}/ValueSet?name=LoincGroupLG51020-2
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### ValueSet $expand by url
GET {{baseUrl}}/ValueSet/$expand?url=http://loinc.org/vs/LG51020-2&displayLanguage=es&count=10&offset=0
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### ValueSet $expand by url first page
GET {{baseUrl}}/ValueSet/$expand?url=http://loinc.org/vs/LG51020-2&displayLanguage=es&count=25&offset=0
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### ValueSet $expand by url second page
GET {{baseUrl}}/ValueSet/$expand?url=http://loinc.org/vs/LG51020-2&displayLanguage=es&count=25&offset=25
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### ValueSet $expand by url small page size
GET {{baseUrl}}/ValueSet/$expand?url=http://loinc.org/vs/LG51020-2&displayLanguage=es&count=5&offset=0
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### ValueSet $expand by id
GET {{baseUrl}}/ValueSet/loinc-group-LG51020-2/$expand?displayLanguage=es&count=10&offset=0
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### ValueSet $expand by id first page
GET {{baseUrl}}/ValueSet/loinc-group-LG51020-2/$expand?displayLanguage=es&count=25&offset=0
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### ValueSet $expand by id second page
GET {{baseUrl}}/ValueSet/loinc-group-LG51020-2/$expand?displayLanguage=es&count=25&offset=25
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### ValueSet $expand by id deep offset
GET {{baseUrl}}/ValueSet/loinc-group-LG51020-2/$expand?displayLanguage=es&count=25&offset=250
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}
