@baseUrl = http://localhost:52774/csp/healthshare/terminology/fhir/r4
@username = superuser
@password = SYS
@valueSetId = 900000000000497000
@conceptCode = 22298006

### CapabilityStatement
GET {{baseUrl}}/metadata
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### TODO: TerminologyCapabilities
GET {{baseUrl}}/metadata?mode=terminology
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### CodeSystem read by id
GET {{baseUrl}}/CodeSystem/snomed
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### CodeSystem search
GET {{baseUrl}}/CodeSystem
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### CodeSystem search by url
GET {{baseUrl}}/CodeSystem?url=http://snomed.info/sct
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### CodeSystem search by name
GET {{baseUrl}}/CodeSystem?name=SNOMEDCT
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### CodeSystem $lookup by code
GET {{baseUrl}}/CodeSystem/$lookup?system=http://snomed.info/sct&code={{conceptCode}}&displayLanguage=es
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### CodeSystem instance $lookup by code
GET {{baseUrl}}/CodeSystem/snomed/$lookup?code={{conceptCode}}&displayLanguage=es
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### CodeSystem $validate-code by code
GET {{baseUrl}}/CodeSystem/$validate-code?system=http://snomed.info/sct&code={{conceptCode}}
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### CodeSystem instance $validate-code by code
GET {{baseUrl}}/CodeSystem/snomed/$validate-code?code={{conceptCode}}
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### CodeSystem $subsumes by code pair
GET {{baseUrl}}/CodeSystem/$subsumes?system=http://snomed.info/sct&codeA={{conceptCode}}&codeB=404684003
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### CodeSystem $subsumes equivalent example
GET {{baseUrl}}/CodeSystem/$subsumes?system=http://snomed.info/sct&codeA={{conceptCode}}&codeB={{conceptCode}}
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### CodeSystem instance $subsumes by code pair
GET {{baseUrl}}/CodeSystem/snomed/$subsumes?codeA=404684003&codeB={{conceptCode}}
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### ValueSet read by id
GET {{baseUrl}}/ValueSet/{{valueSetId}}
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### ValueSet $expand by id
GET {{baseUrl}}/ValueSet/{{valueSetId}}/$expand?displayLanguage=es&count=10&offset=0
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### ValueSet $expand by url
GET {{baseUrl}}/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs=refset/{{valueSetId}}&displayLanguage=es&count=10&offset=0
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### ValueSet search
GET {{baseUrl}}/ValueSet
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### ValueSet search by url
GET {{baseUrl}}/ValueSet?url=http://snomed.info/sct?fhir_vs=refset/900000000000489007
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}

### ValueSet search by name
GET {{baseUrl}}/ValueSet?name=SnomedRefset446608001
Accept: application/fhir+json
Authorization: Basic {{username}}:{{password}}
