Class Terminology.Production.Msg.CIEGetChildrenResponse Extends Ens.Response
{

Property Payload As Terminology.CIE.DTO.HierarchyResult;

Storage Default
{
<Data name="CIEGetChildrenResponseDefaultData">
<Subscript>"CIEGetChildrenResponse"</Subscript>
<Value name="1">
<Value>Payload</Value>
</Value>
</Data>
<DefaultData>CIEGetChildrenResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
