Class Terminology.Production.Msg.CIEGetFamiliesResponse Extends Ens.Response
{

Property Payload As Terminology.CIE.DTO.FamilyResult;

Storage Default
{
<Data name="CIEGetFamiliesResponseDefaultData">
<Subscript>"CIEGetFamiliesResponse"</Subscript>
<Value name="1">
<Value>Payload</Value>
</Value>
</Data>
<DefaultData>CIEGetFamiliesResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
