Class Terminology.Production.Msg.CIEGetAncestorsResponse Extends Ens.Response
{

Property Payload As Terminology.CIE.DTO.HierarchyResult;

Storage Default
{
<Data name="CIEGetAncestorsResponseDefaultData">
<Subscript>"CIEGetAncestorsResponse"</Subscript>
<Value name="1">
<Value>Payload</Value>
</Value>
</Data>
<DefaultData>CIEGetAncestorsResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
