Class Terminology.Production.Msg.CIEGetDescendantsResponse Extends Ens.Response
{

Property Payload As Terminology.CIE.DTO.HierarchyResult;

Storage Default
{
<Data name="CIEGetDescendantsResponseDefaultData">
<Subscript>"CIEGetDescendantsResponse"</Subscript>
<Value name="1">
<Value>Payload</Value>
</Value>
</Data>
<DefaultData>CIEGetDescendantsResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
