Class Terminology.Production.Msg.CIEValidateCodeResponse Extends Ens.Response
{

Property Payload As Terminology.CIE.DTO.ValidateCodeResult;

Storage Default
{
<Data name="CIEValidateCodeResponseDefaultData">
<Subscript>"CIEValidateCodeResponse"</Subscript>
<Value name="1">
<Value>Payload</Value>
</Value>
</Data>
<DefaultData>CIEValidateCodeResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
