Class Terminology.Production.Msg.ICDGetDescendantsResponse Extends Ens.Response
{

Property Payload As Terminology.ICD.DTO.HierarchyResult;

Storage Default
{
<Data name="ICDGetDescendantsResponseDefaultData">
<Subscript>"ICDGetDescendantsResponse"</Subscript>
<Value name="1">
<Value>Payload</Value>
</Value>
</Data>
<DefaultData>ICDGetDescendantsResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
