Class Terminology.Production.Msg.ICDGetAncestorsResponse Extends Ens.Response
{

Property Payload As Terminology.ICD.DTO.HierarchyResult;

Storage Default
{
<Data name="ICDGetAncestorsResponseDefaultData">
<Subscript>"ICDGetAncestorsResponse"</Subscript>
<Value name="1">
<Value>Payload</Value>
</Value>
</Data>
<DefaultData>ICDGetAncestorsResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
