Class Terminology.Production.Msg.ICDGetChildrenResponse Extends Ens.Response
{

Property Payload As Terminology.ICD.DTO.HierarchyResult;

Storage Default
{
<Data name="ICDGetChildrenResponseDefaultData">
<Subscript>"ICDGetChildrenResponse"</Subscript>
<Value name="1">
<Value>Payload</Value>
</Value>
</Data>
<DefaultData>ICDGetChildrenResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
