Class Terminology.Production.Msg.ICDGetFamiliesResponse Extends Ens.Response
{

Property Payload As Terminology.ICD.DTO.FamilyResult;

Storage Default
{
<Data name="ICDGetFamiliesResponseDefaultData">
<Subscript>"ICDGetFamiliesResponse"</Subscript>
<Value name="1">
<Value>Payload</Value>
</Value>
</Data>
<DefaultData>ICDGetFamiliesResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
