Class Terminology.Production.Msg.ICDValidateCodeResponse Extends Ens.Response
{

Property Payload As Terminology.ICD.DTO.ValidateCodeResult;

Storage Default
{
<Data name="ICDValidateCodeResponseDefaultData">
<Subscript>"ICDValidateCodeResponse"</Subscript>
<Value name="1">
<Value>Payload</Value>
</Value>
</Data>
<DefaultData>ICDValidateCodeResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
