Class Terminology.Production.Msg.SnomedGetRefsetMembersResponse Extends Ens.Response
{

Property Payload As Terminology.Snomed.DTO.RefsetMemberListResult;

Storage Default
{
<Data name="SnomedGetRefsetMembersResponseDefaultData">
<Subscript>"SnomedGetRefsetMembersResponse"</Subscript>
<Value name="1">
<Value>Payload</Value>
</Value>
</Data>
<DefaultData>SnomedGetRefsetMembersResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
