Class Terminology.Production.Msg.SnomedGetIcd10MappingsResponse Extends Ens.Response
{

Property Payload As Terminology.Snomed.DTO.Icd10MappingResult;

Storage Default
{
<Data name="SnomedGetIcd10MappingsResponseDefaultData">
<Subscript>"SnomedGetIcd10MappingsResponse"</Subscript>
<Value name="1">
<Value>Payload</Value>
</Value>
</Data>
<DefaultData>SnomedGetIcd10MappingsResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
