Class Terminology.Production.Msg.SnomedGetAncestorsResponse Extends Ens.Response
{

Property Payload As Terminology.Snomed.DTO.ConceptListResult;

Storage Default
{
<Data name="SnomedGetAncestorsResponseDefaultData">
<Subscript>"SnomedGetAncestorsResponse"</Subscript>
<Value name="1">
<Value>Payload</Value>
</Value>
</Data>
<DefaultData>SnomedGetAncestorsResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
