Class Terminology.Production.Msg.SnomedGetChildrenResponse Extends Ens.Response
{

Property Payload As Terminology.Snomed.DTO.ConceptListResult;

Storage Default
{
<Data name="SnomedGetChildrenResponseDefaultData">
<Subscript>"SnomedGetChildrenResponse"</Subscript>
<Value name="1">
<Value>Payload</Value>
</Value>
</Data>
<DefaultData>SnomedGetChildrenResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
