Class Terminology.Production.Msg.SnomedGetConceptResponse Extends Ens.Response
{

Property Payload As Terminology.Snomed.DTO.ConceptResult;

Storage Default
{
<Data name="SnomedGetConceptResponseDefaultData">
<Subscript>"SnomedGetConceptResponse"</Subscript>
<Value name="1">
<Value>Payload</Value>
</Value>
</Data>
<DefaultData>SnomedGetConceptResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
