Class Terminology.Production.Msg.SnomedGetDescendantsResponse Extends Ens.Response
{

Property Payload As Terminology.Snomed.DTO.ConceptListResult;

Storage Default
{
<Data name="SnomedGetDescendantsResponseDefaultData">
<Subscript>"SnomedGetDescendantsResponse"</Subscript>
<Value name="1">
<Value>Payload</Value>
</Value>
</Data>
<DefaultData>SnomedGetDescendantsResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
