Class Terminology.Production.Msg.SnomedGetDescriptionsResponse Extends Ens.Response
{

Property Payload As Terminology.Snomed.DTO.DescriptionListResult;

Storage Default
{
<Data name="SnomedGetDescriptionsResponseDefaultData">
<Subscript>"SnomedGetDescriptionsResponse"</Subscript>
<Value name="1">
<Value>Payload</Value>
</Value>
</Data>
<DefaultData>SnomedGetDescriptionsResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
