Class Terminology.Production.Msg.SnomedGetRefsetsResponse Extends Ens.Response
{

Property Payload As Terminology.Snomed.DTO.RefsetListResult;

Storage Default
{
<Data name="SnomedGetRefsetsResponseDefaultData">
<Subscript>"SnomedGetRefsetsResponse"</Subscript>
<Value name="1">
<Value>Payload</Value>
</Value>
</Data>
<DefaultData>SnomedGetRefsetsResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
