Class Terminology.Production.Msg.SnomedValidateCodeResponse Extends Ens.Response
{

Property Payload As Terminology.Snomed.DTO.ValidateCodeResult;

Storage Default
{
<Data name="SnomedValidateCodeResponseDefaultData">
<Subscript>"SnomedValidateCodeResponse"</Subscript>
<Value name="1">
<Value>Payload</Value>
</Value>
</Data>
<DefaultData>SnomedValidateCodeResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
