Class Terminology.Production.Msg.SnomedGetSubsumesResponse Extends Ens.Response
{

Property Payload As Terminology.Snomed.DTO.SubsumesResult;

Storage Default
{
<Data name="SnomedGetSubsumesResponseDefaultData">
<Subscript>"SnomedGetSubsumesResponse"</Subscript>
<Value name="1">
<Value>Payload</Value>
</Value>
</Data>
<DefaultData>SnomedGetSubsumesResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
