Class Terminology.Production.Msg.VectorCrosswalkResponse Extends Ens.Response
{

Property Payload As Terminology.Vector.DTO.CrosswalkResult;

Storage Default
{
<Data name="VectorCrosswalkResponseDefaultData">
<Subscript>"VectorCrosswalkResponse"</Subscript>
<Value name="1">
<Value>Payload</Value>
</Value>
</Data>
<DefaultData>VectorCrosswalkResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
