zn "%SYS"

do ##class(SYS.Container).QuiesceForBundling()
do ##class(Security.Users).UnExpireUserPasswords("*")

zn "TERMINOLOGY"

set sc = $SYSTEM.OBJ.LoadDir("/opt/irisapp/src/Terminology", "ck", , 1)
set status = ##class(HS.FHIRServer.Installer).InteropAdapterConfig("/terminology/r5")
set production = "Terminology.Production"
set ^Ens.Configuration("csp","LastProduction") = production
do ##class(Ens.Director).SetAutoStart(production)
do ##class(Ens.Director).StartProduction(production)